### ISSUE TITLE
docker-compose example showing Southpaw working end to end

### ISSUE THREAD

**Issue by ksindi** [jwplayer/southpaw#8]
It would be nice to have a docker-compose example showing Southpaw working end to end

**Comment by davidstoker** [comment]
Hello, mind if I ask what happened to the closed PR that's referenced here that had an example?

I stumbled on this project today when looking to solve the exact problems that this is for and I used some of the work from that PR to get my own proof of concept up and running locally. Would be a nice example to have in the project!

**Comment by eric-weaver** [comment]
Hello @davidstoker, we appreciate your interest in Southpaw and I'm glad you were able to get something running locally based off of this slightly dated example! 

An example of how to get it setup is something we really want to get into Southpaw but have not had the time to get a nice concise example. The previous PR was closed because it had grown stale from inactivity and had some issues with upstream dependencies. We also wanted to simplify it a bit by removing some of the dependencies like debezium which might be confusing to people since this is not necessary to use Southpaw.


We also welcome contributions if this is something you feel like you would like to add!

**Comment by davidstoker** [comment]
Makes perfect sense. I appreciate the quick response and thank you for publishing the project in the first place!

Would you envision having both a simple example and one that involves Debezium or just keep Debezium out of it in general?

**Comment by ksindi** [comment]
@davidstoker mostly the latter without Debezium. Would you find more value in an end to end example with Debezium?
